### ISSUE TITLE
TypeError: 'mozMatchesSelector' called on an object that does not implement interface Element.

### ISSUE THREAD

**Issue by zamakkat** [madebymany/sir-trevor-js#455]
I am trying to initialize `sir-trevor` and the latest version `0.6.0-beta9` doesn't work for me - the textarea is left as-is. (I also tried `beta1`, `beta7`, `beta8`). My code is really simple, just follows the docs on how to init it:
```js
new SirTrevor.Editor({ el: $('.js-st-instance') });
```
HTML has a `form` with a `textarea` with a `js-st-instance` class.

Doesn't work with Firefox, Firefox Developer and Chrome. Here are the errors they return in the console:
- Firefox
```
(warning) mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create
(error) TypeError: 'mozMatchesSelector' called on an object that does not implement interface Element.
```
- Chrome
```
Uncaught TypeError: Illegal invocation
```

The same setup works with `sir-trevor` version `0.5.0` so that's what I am using right now... Tried having a look at the source but no idea how exactly to fix it.

**Comment by raffij** [comment]
Hi,

In 0.6 jQuery has been removed internally.

So you'll now want to call the initialiser with a native element.

```js
new SirTrevor.Editor({ el: $('.js-st-instance')[0] });

// or

new SirTrevor.Editor({ el: document.querySelector('.js-st-instance') });
```

More info can be found https://github.com/madebymany/sir-trevor-js/blob/master/docs/migrations/0.5-0.6.md

**Comment by zamakkat** [comment]
Oh OK thanks a lot. I was assuming that the documentation at http://madebymany.github.io/sir-trevor-js/docs.html was up to date with the latest version.
